version: '3'

tasks:
  build:
    cmds:
      - make
    silent: true
  run:
    cmds:
      - cat /proc/perftop
    silent: true
  load_perftop:
    cmds:
      - sudo insmod kprobe_stack_trace_save.ko
      - sudo insmod kretprobe_perftop_show.ko
    silent: true
  unload_perftop:
    cmds:
      - sudo rmmod kprobe_stack_trace_save
      - sudo rmmod kretprobe_perftop_show
    silent: true
  clean:
    cmds:
      - make clean
    silent: true
